### ISSUE TITLE
KWin's rules can do this + programs can trigger it

### ISSUE THREAD

**Issue by jankusanagi** [murat-cileli/compositor-switcher-for-kde#1]
Not to discourage you from making your program, but Plasma's window manager, KWin, can do this natively on a per-program or per-window basis, using its own rule engine.

Just right-click the title bar in the target program → More actions → Special Application Settings, and enjoy the many, many possibilities KWin offers. Blocking compositing for that whole program or that specific window is an option in the "Appearance and Fixes" tab.

Besides the user manually setting this things to their liking, well done programs can **ask** the WM to disable compositing for their particular windows, directly, and Plasma's window manager will obey such requests.

Cheers!

**Comment by murat-cileli** [comment]
Thank you for information @jankusanagi . I wrote this tool for my personel use but shared anyway. Controlling compositor state by proccess name, more easy for me. For example, it's hard to right click to fullscreen applications (e.g. MAME). OK, you can do this in settings but as I metioned, it's hard way for me. This simple tool is an alternative for anyone think like me.

**Comment by jankusanagi** [comment]
If the window is fullscreen, you just hit Alt+F3.

It's also highly inefficient to run "/bin/bash" (which might not even be there) to then run "qdbus" everytime you want to send a DBus command to KWin. You should look into using DBus natively.

**Comment by murat-cileli** [comment]
Thanks fot the tip @jankusanagi . What should I do? Removing this tool is good for the community?

**Comment by jankusanagi** [comment]
Ah no no, I see no reason to remove anything.

But maybe you could add that information to the README, so people who find this tool looking to solve that same issue, can choose between using this program, or using KWin's features they probably didn't know about =)

**Comment by murat-cileli** [comment]
@jankusanagi . Great! I'm updating the read me file and and find a way to use DBus natively. Thanks for your suggestions.
